services:
    application:
        image: node:18
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        ports:
            - '${APP_PORT}:${APP_PORT}'
        environment:
            - DATABASE_URL=${DATABASE_URL}
        command: npm start
    database:
        image: postgres:latest
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./data:/var/lib/postgresql/data:rw
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - '${POSTGRES_PORT}:${POSTGRES_PORT}'
